### PR TITLE
m3-reflection

### PR DESCRIPTION
**Pull request by czwcandy**
reflection for milestone3 written based on the discussion during lab and issues recorded. Please review.

### CODE REVIEW

**Review by sivakornchong — CHANGES_REQUESTED** [review]
-   **Widget Control Clarifications**: Distinguishing between global and local controls will be refined to enhance user intuitiveness.

-   **Further Visual Adjustments**: Additional aesthetic enhancements, such as aligning titles and adding background colors, are on our agenda for further polish.

These two points are already implemented. 

We need to compare with the sketch in milestone 1 too and highlight any difference. 

Milestone query:
In this section, your group should clearly document which additional parts of your proposal/sketch you have implemented in your dashboard since milestone 1 and explain what is not yet implemented.
For anything that you have done differently than in your proposal/sketch explain why (e.g. implementation difficulty, explanation for why the new approach is more effective, etc).

**Comment by czwcandy** [comment]
please see slack, joel said it is the typo, we only need to compare with milestone2, not milestone1.

**Comment by sivakornchong** [comment]
Ok, then please help to edit the two changes I mentioned to implemented

**Comment by czwcandy** [comment]
I moved these two parts in Feedback Implementation. Please review again, Thank you

**Review by sivakornchong — APPROVED** [review]
Great change! Thank you

**Pull request merged**
