### PR TITLE
adding app description and sketch to the proposal file

### LINKED ISSUE #22: Adding Dashboard Description and Sketch in m1_proposal

### PR DESCRIPTION
**Pull request by WeilinHan8**
Hi team,

Please review app sketch and app description part, and let me know if you have any feedback

thanks!

### CODE REVIEW

**Review by sivakornchong — APPROVED** [review]
Great write up. Thanks!

**Review by AnuBanga — CHANGES_REQUESTED** [review]
First part of change is not for our dashboard. Please verify and make changes accordingly.

**Comment by AnuBanga** [comment]
> First part of change is not for our dashboard. Please verify and make changes accordingly.

Please ignore. You have already removed sample from the write up.

**Review by AnuBanga — APPROVED** [review]
Looks great. Review has been completed.

**Pull request merged**
